# =============================================================================
# core/variables/network.auto.tfvars
#
# DO NOT EDIT MANUALLY.
# Generated by scripts/replace-vars.sh from:
#   environment/<ENV>/security/network.yaml
#   environment/<ENV>/zoning/*.yml
#
# Regenerate:
#   ./scripts/replace-vars.sh dev
# =============================================================================


vpc_name = "REPLACE_VPC_NAME"
vpc_cidr = "REPLACE_VPC_CIDR"

availability_zones = REPLACE_AVAILABILITY_ZONES

enable_nat_gateway = REPLACE_NAT_ENABLED
single_nat_gateway = REPLACE_NAT_SINGLE

# Keyed by zone name — populated from environment/<ENV>/zoning/*.yml
subnet_zones = REPLACE_SUBNET_ZONES

private_ip_assignments = {}

common_tags = {
  environment  = "REPLACE_ENVIRONMENT"
  program      = "REPLACE_PROGRAM"
  organisation = "REPLACE_ORGANISATION"
  managed_by   = "terraform"
}
