# =============================================================================
# core/variables/security.auto.tfvars
#
# DO NOT EDIT MANUALLY.
# Generated by scripts/replace-vars.sh from:
#   environment/<ENV>/security/rules.yaml   → SG and NACL rules
#   environment/<ENV>/security/network.yaml → subnet types drive NACL scope
#
# Regenerate:
#   ./scripts/replace-vars.sh <sid>   e.g. replace-vars.sh kr-carevo
# =============================================================================

sg_ingress_rules = REPLACE_SG_INGRESS

sg_egress_rules = REPLACE_SG_EGRESS

nacl_inbound_rules  = REPLACE_NACL_PRIVATE_INBOUND

nacl_outbound_rules = REPLACE_NACL_PRIVATE_OUTBOUND

nacl_public_inbound_rules  = REPLACE_NACL_PUBLIC_INBOUND

nacl_public_outbound_rules = REPLACE_NACL_PUBLIC_OUTBOUND
